export const notificationData = [
    {
        "id": 1,
        "category": "alert",
        "message": "Unusual Behaviour Detected",
        "description": "1 match has been flagged for suspicious performance behaviour by its participants.",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },
        "read": false
    },
    {
        "id": 2,
        "category": "issue",
        "message": "Result Approval Required",
        "description": "Quarter-Finals round has concluded. 4 games are awaiting your approval of their results.",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },
        "read": false
    },
    {
        "id": 3,
        "category": "notification",
        "message": "Cron Job Started",
        "description": "Tournament has commenced - started by Cron Job at 18:00",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },        
        "read": true
    },
    {
        "id": 4,
        "category": "notification",
        "message": "Test Message",
        "description": "This is some text that is supposed to be very long to check if the line clamp function works properly because I cannot think of any other way to test this functionality.",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },        
        "read": true
    },
]

export const tournamentCardData = [
    {
        "id": "1",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 20,
        "testCaseWeight": 50,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-17T03:24:00"),
    },
    {
        "id": "2",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "double-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 40,
        "memWeight": 15,
        "testCaseWeight": 45,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-10-17T03:24:00"),
    },
    {
        "id": "3",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "middle",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "COMPLETED",
        "signUpPercentage": 30,
        "numberOfSignups": 10,
        "capacity": 32,
        "timeWeight": 69,
        "memWeight": 31,
        "testCaseWeight": 0,
        "currentRound": "Final",
        "currentRoundEndDate": new Date("2023-12-17T03:24:00"),
    },
    {
        "id": "4",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "ONGOING",
        "signUpPercentage": 85,
        "numberOfSignups": 13,
        "capacity": 16,
        "timeWeight": 50,
        "memWeight": 35,
        "testCaseWeight": 15,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-11-17T03:24:00"),
    },
    {
        "id": "5",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "lower",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "COMPLETED",
        "signUpPercentage": 50,
        "numberOfSignups": 32,
        "capacity": 64,
        "timeWeight": 40,
        "memWeight": 0,
        "testCaseWeight": 60,
        "currentRound": "Grand Finals",
        "currentRoundEndDate": new Date("2024-06-17T03:24:00"),
    },
    {
        "id": "6",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-07T03:24:00"),
    },
    {
        "id": "7",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-07T03:24:00"),
    },
    {
        "id": "8",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-07T03:24:00"),
    },
    {
        "id": "9",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date(),
        "endDate": new Date(),
        "signupEndDate": new Date(),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-07T03:24:00"),
    },
]

export const userTournamentCardData = [
    {
        "id": "1",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-18T03:24:00"),
        "endDate": new Date("2024-12-17T03:24:00"),
        "signupEndDate": new Date("2024-10-16T03:24:00"),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 20,
        "testCaseWeight": 50,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-12-17T03:24:00"),
        "signedUp": true,
        "participated": false,
        "signpsOpen": true,
        "placing": -1,
    },
    {
        "id": "2",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "double-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-02T03:24:00"),
        "endDate": new Date("2024-12-22T03:24:00"),
        "signupEndDate": new Date("2024-10-01T03:24:00"),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 40,
        "memWeight": 15,
        "testCaseWeight": 45,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-10-17T03:24:00"),
        "signedUp": true,
        "participated": true,
        "signpsOpen": false,
        "placing": -1,
    },
    {
        "id": "3",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "middle",
        "startDate": new Date("2024-09-05T03:24:00"),
        "endDate": new Date("2024-09-07T03:24:00"),
        "signupEndDate": new Date("2024-09-03T03:24:00"),
        "status": "COMPLETED",
        "signUpPercentage": 30,
        "numberOfSignups": 10,
        "capacity": 32,
        "timeWeight": 69,
        "memWeight": 31,
        "testCaseWeight": 0,
        "currentRound": "Final",
        "currentRoundEndDate": new Date("2023-09-07T03:24:00"),
        "signedUp": true,
        "participated": true,
        "signpsOpen": false,
        "placing": 6,
    },
    {
        "id": "4",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-27T03:24:00"),
        "endDate": new Date("2024-10-30T03:24:00"),
        "signupEndDate": new Date("2024-10-22T03:24:00"),
        "status": "ONGOING",
        "signUpPercentage": 85,
        "numberOfSignups": 13,
        "capacity": 16,
        "timeWeight": 50,
        "memWeight": 35,
        "testCaseWeight": 15,
        "currentRound": "Quarter-Finals",
        "currentRoundEndDate": new Date("2024-11-17T03:24:00"),
        "signedUp": false,
        "participated": false,
        "signpsOpen": true,
        "placing": -1,
    },
    {
        "id": "5",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "lower",
        "startDate": new Date("2024-06-01T03:24:00"),
        "endDate": new Date("2024-06-17T03:24:00"),
        "signupEndDate": new Date("2024-05-31T03:24:00"),
        "status": "COMPLETED",
        "signUpPercentage": 50,
        "numberOfSignups": 32,
        "capacity": 64,
        "timeWeight": 40,
        "memWeight": 0,
        "testCaseWeight": 60,
        "currentRound": "Grand Finals",
        "currentRoundEndDate": new Date("2024-06-17T03:24:00"),
        "signedUp": false,
        "participated": true,
        "signpsOpen": false,
        "placing": 23,
    },
    {
        "id": "6",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-08-20T03:24:00"),
        "endDate": new Date("2024-10-29T03:24:00"),
        "signupEndDate": new Date("2024-08-17T03:24:00"),
        "status": "ONGOING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Round of 16",
        "currentRoundEndDate": new Date("2024-10-15T03:24:00"),
        "signedUp": true,
        "participated": false,
        "signpsOpen": false,
        "placing": -1,
    },
    {
        "id": "7",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-20T03:24:00"),
        "endDate": new Date("2024-10-29T03:24:00"),
        "signupEndDate": new Date("2024-10-17T03:24:00"),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Round of 16",
        "currentRoundEndDate": new Date("2024-10-15T03:24:00"),
        "signedUp": false,
        "participated": false,
        "signpsOpen": true,
        "placing": -1,
    },
    {
        "id": "8",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-20T03:24:00"),
        "endDate": new Date("2024-10-29T03:24:00"),
        "signupEndDate": new Date("2024-10-17T03:24:00"),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Round of 16",
        "currentRoundEndDate": new Date("2024-10-15T03:24:00"),
        "signedUp": false,
        "participated": false,
        "signpsOpen": true,
        "placing": -1,
    },
    {
        "id": "9",
        "icon": "smu-logo.png",
        "name": "SMU Gardening Championships",
        "format": "single-elimination",
        "band": "upper",
        "startDate": new Date("2024-10-20T03:24:00"),
        "endDate": new Date("2024-10-29T03:24:00"),
        "signupEndDate": new Date("2024-10-17T03:24:00"),
        "status": "UPCOMING",
        "signUpPercentage": 60,
        "numberOfSignups": 38,
        "capacity": 64,
        "timeWeight": 30,
        "memWeight": 10,
        "testCaseWeight": 60,
        "currentRound": "Round of 16",
        "currentRoundEndDate": new Date("2024-10-15T03:24:00"),
        "signedUp": false,
        "participated": false,
        "signpsOpen": true,
        "placing": -1,
    },
]

export const userNotificationData = [
    {
        "id": 1,
        "category": "alert",
        "message": "Round Ending Soon",
        "description": "Your have an uncompleted round in this tournament. Please attempt the round before it ends. Failure to do so will result in a walkover for your opponent",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },
        "read": false
    },
    {
        "id": 2,
        "category": "issue",
        "message": "Performance Update Required",
        "description": "Please review your submitted code.",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },
        "read": false
    },
    {
        "id": 3,
        "category": "notification",
        "message": "Tournament Registration Approved",
        "description": "Congratulations! You have been accepted into this tournament, which will commence on 14 Oct 2024, 12:00",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },        
        "read": true
    },
    {
        "id": 4,
        "category": "notification",
        "message": "Test Message",
        "description": "This is some text that is supposed to be very long to check if the line clamp function works properly because I cannot think of any other way to test this functionality.",
        "datetime": new Date(),
        "tournament": {
            "id": 1,
            "name": "SMU Gardening Championships"
        },        
        "read": true
    },
]

export const tournamentCardData2 = [
    {
        id: "1",
        icon: "smu-logo.png",
        name: "Summer Coding Challenge 2024",
        capacity: 32,
        format: "single-elimination",
        band: "upper",
        startDate: new Date("2024-08-15T09:00:00").toISOString(),
        endDate: new Date("2024-08-20T18:00:00").toISOString(),
        signupStartDate: new Date("2024-07-01T12:00:00").toISOString(),
        signupEndDate: new Date("2024-08-10T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 60,
        numberOfSignups: 30,
        timeWeight: 40,
        memWeight: 30,
        testCaseWeight: 30,
        currentRound: "Not Started",
        currentRoundEndDate: new Date("2024-12-17T03:24:00").toISOString(),
        signupsOpen: false
    },
    {
        id: "2",
        icon: "smu-logo.png",
        name: "SMU Soccer Showdown",
        capacity: 128,
        format: "double-elimination",
        band: "lower",
        startDate: new Date("2024-11-20T10:00:00").toISOString(),
        endDate: new Date("2024-12-25T16:00:00").toISOString(),
        signupStartDate: new Date("2024-11-01T08:00:00").toISOString(),
        signupEndDate: new Date("2024-11-19T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 128,
        timeWeight: 25,
        memWeight: 35,
        testCaseWeight: 40,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-12-25T12:00:00").toISOString(),
        signupsOpen: false
    },
    {
        id: "3",
        icon: "smu-logo.png",
        name: "SMU Chess Grand Masters",
        capacity: 32,
        format: "round-robin",
        band: "upper",
        startDate: new Date("2024-10-01T09:00:00").toISOString(),
        endDate: new Date("2024-10-15T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-20T09:00:00").toISOString(),
        signupEndDate: new Date("2024-09-30T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 50,
        numberOfSignups: 16,
        timeWeight: 40,
        memWeight: 30,
        testCaseWeight: 30,
        currentRound: "Group Stage",
        currentRoundEndDate: new Date("2024-10-10T18:00:00").toISOString(),
        signupsOpen: true
    },
    {
        id: "4",
        icon: "smu-logo.png",
        name: "SMU Badminton Open",
        capacity: 64,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-12-10T09:00:00").toISOString(),
        endDate: new Date("2024-12-18T18:00:00").toISOString(),
        signupStartDate: new Date("2024-11-20T09:00:00").toISOString(),
        signupEndDate: new Date("2024-12-09T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 70,
        numberOfSignups: 45,
        timeWeight: 35,
        memWeight: 25,
        testCaseWeight: 40,
        currentRound: "Preliminary",
        currentRoundEndDate: new Date("2024-12-17T10:00:00").toISOString(),
        signupsOpen: true
    },
    {
        id: "5",
        icon: "smu-logo.png",
        name: "SMU Tennis League",
        capacity: 32,
        format: "round-robin",
        band: "upper",
        startDate: new Date("2024-11-01T10:00:00").toISOString(),
        endDate: new Date("2024-11-10T18:00:00").toISOString(),
        signupStartDate: new Date("2024-10-15T09:00:00").toISOString(),
        signupEndDate: new Date("2024-10-31T23:59:00").toISOString(),
        status: "ONGOING",
        signUpPercentage: 90,
        numberOfSignups: 29,
        timeWeight: 30,
        memWeight: 30,
        testCaseWeight: 40,
        currentRound: "Semi-Finals",
        currentRoundEndDate: new Date("2024-11-08T14:00:00").toISOString(),
        signupsOpen: false
    },
    {
        id: "6",
        icon: "smu-logo.png",
        name: "SMU Basketball Dunk Fest",
        capacity: 128,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-09-15T08:00:00").toISOString(),
        endDate: new Date("2024-10-01T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-01T08:00:00").toISOString(),
        signupEndDate: new Date("2024-09-14T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 128,
        timeWeight: 35,
        memWeight: 25,
        testCaseWeight: 40,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-09-30T18:00:00").toISOString(),
        signupsOpen: false
    },
    {
        id: "7",
        icon: "smu-logo.png",
        name: "SMU Esports Tournament",
        capacity: 64,
        format: "double-elimination",
        band: "upper",
        startDate: new Date("2024-10-05T10:00:00").toISOString(),
        endDate: new Date("2024-10-25T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-15T10:00:00").toISOString(),
        signupEndDate: new Date("2024-10-04T23:59:00").toISOString(),
        status: "ONGOING",
        signUpPercentage: 80,
        numberOfSignups: 51,
        timeWeight: 30,
        memWeight: 40,
        testCaseWeight: 30,
        currentRound: "Quarter-Finals",
        currentRoundEndDate: new Date("2024-10-22T18:00:00").toISOString(),
        signupsOpen: false
    },
    {
        id: "8",
        icon: "smu-logo.png",
        name: "SMU Golf Open",
        capacity: 64,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-08-25T10:00:00").toISOString(),
        endDate: new Date("2024-09-05T18:00:00").toISOString(),
        signupStartDate: new Date("2024-08-01T10:00:00").toISOString(),
        signupEndDate: new Date("2024-08-24T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 64,
        timeWeight: 25,
        memWeight: 30,
        testCaseWeight: 45,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-09-04T18:00:00").toISOString(),
        signupsOpen: false
    },
]

export const userTournamentCardData2 = [
    {
        id: "1",
        icon: "smu-logo.png",
        name: "Summer Coding Challenge 2024",
        capacity: 32,
        format: "single-elimination",
        band: "upper",
        startDate: new Date("2024-08-15T09:00:00").toISOString(),
        endDate: new Date("2024-08-20T18:00:00").toISOString(),
        signupStartDate: new Date("2024-07-01T12:00:00").toISOString(),
        signupEndDate: new Date("2024-08-10T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 60,
        numberOfSignups: 30,
        timeWeight: 40,
        memWeight: 30,
        testCaseWeight: 30,
        currentRound: "Not Started",
        currentRoundEndDate: new Date("2024-12-17T03:24:00").toISOString(),
        signedUp: false,
        participated: false,
        signupsOpen: true,
        placing: -1,
    },
    {
        id: "2",
        icon: "smu-logo.png",
        name: "SMU Soccer Showdown",
        capacity: 128,
        format: "double-elimination",
        band: "lower",
        startDate: new Date("2024-11-20T10:00:00").toISOString(),
        endDate: new Date("2024-12-25T16:00:00").toISOString(),
        signupStartDate: new Date("2024-11-01T08:00:00").toISOString(),
        signupEndDate: new Date("2024-11-19T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 128,
        timeWeight: 25,
        memWeight: 35,
        testCaseWeight: 40,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-12-25T12:00:00").toISOString(),
        signedUp: true,
        participated: true,
        signupsOpen: false,
        placing: 1, // Finished first place
    },
    {
        id: "3",
        icon: "smu-logo.png",
        name: "SMU Chess Grand Masters",
        capacity: 32,
        format: "round-robin",
        band: "upper",
        startDate: new Date("2024-10-01T09:00:00").toISOString(),
        endDate: new Date("2024-10-15T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-20T09:00:00").toISOString(),
        signupEndDate: new Date("2024-09-30T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 50,
        numberOfSignups: 16,
        timeWeight: 40,
        memWeight: 30,
        testCaseWeight: 30,
        currentRound: "Group Stage",
        currentRoundEndDate: new Date("2024-10-10T18:00:00").toISOString(),
        signedUp: false,
        participated: false,
        signupsOpen: true,
        placing: -1,
    },
    {
        id: "4",
        icon: "smu-logo.png",
        name: "SMU Badminton Open",
        capacity: 64,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-12-10T09:00:00").toISOString(),
        endDate: new Date("2024-12-18T18:00:00").toISOString(),
        signupStartDate: new Date("2024-11-20T09:00:00").toISOString(),
        signupEndDate: new Date("2024-12-09T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 70,
        numberOfSignups: 45,
        timeWeight: 35,
        memWeight: 25,
        testCaseWeight: 40,
        currentRound: "Preliminary",
        currentRoundEndDate: new Date("2024-12-17T10:00:00").toISOString(),
        signedUp: true,
        participated: false,
        signupsOpen: true,
        placing: -1,
    },
    {
        id: "5",
        icon: "smu-logo.png",
        name: "SMU Tennis League",
        capacity: 32,
        format: "round-robin",
        band: "upper",
        startDate: new Date("2024-11-01T10:00:00").toISOString(),
        endDate: new Date("2024-11-10T18:00:00").toISOString(),
        signupStartDate: new Date("2024-10-15T09:00:00").toISOString(),
        signupEndDate: new Date("2024-10-31T23:59:00").toISOString(),
        status: "ONGOING",
        signUpPercentage: 90,
        numberOfSignups: 29,
        timeWeight: 30,
        memWeight: 30,
        testCaseWeight: 40,
        currentRound: "Semi-Finals",
        currentRoundEndDate: new Date("2024-11-08T14:00:00").toISOString(),
        signedUp: true,
        participated: true,
        signupsOpen: false,
        placing: -1,
    },
    {
        id: "6",
        icon: "smu-logo.png",
        name: "SMU Basketball Dunk Fest",
        capacity: 128,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-09-15T08:00:00").toISOString(),
        endDate: new Date("2024-10-01T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-01T08:00:00").toISOString(),
        signupEndDate: new Date("2024-09-14T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 128,
        timeWeight: 35,
        memWeight: 25,
        testCaseWeight: 40,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-09-30T18:00:00").toISOString(),
        signedUp: true,
        participated: true,
        signupsOpen: false,
        placing: 5,
    },
    {
        id: "7",
        icon: "smu-logo.png",
        name: "SMU Esports Tournament",
        capacity: 64,
        format: "double-elimination",
        band: "upper",
        startDate: new Date("2024-10-05T10:00:00").toISOString(),
        endDate: new Date("2024-10-25T18:00:00").toISOString(),
        signupStartDate: new Date("2024-09-15T10:00:00").toISOString(),
        signupEndDate: new Date("2024-10-04T23:59:00").toISOString(),
        status: "ONGOING",
        signUpPercentage: 80,
        numberOfSignups: 51,
        timeWeight: 30,
        memWeight: 40,
        testCaseWeight: 30,
        currentRound: "Quarter-Finals",
        currentRoundEndDate: new Date("2024-10-22T18:00:00").toISOString(),
        signedUp: true,
        participated: false,
        signupsOpen: false,
        placing: -1,
    },
    {
        id: "8",
        icon: "smu-logo.png",
        name: "SMU Golf Open",
        capacity: 64,
        format: "single-elimination",
        band: "lower",
        startDate: new Date("2024-08-25T10:00:00").toISOString(),
        endDate: new Date("2024-09-05T18:00:00").toISOString(),
        signupStartDate: new Date("2024-08-01T10:00:00").toISOString(),
        signupEndDate: new Date("2024-08-24T23:59:00").toISOString(),
        status: "COMPLETED",
        signUpPercentage: 100,
        numberOfSignups: 64,
        timeWeight: 25,
        memWeight: 30,
        testCaseWeight: 45,
        currentRound: "Final",
        currentRoundEndDate: new Date("2024-09-04T18:00:00").toISOString(),
        signedUp: false,
        participated: false,
        signupsOpen: false,
        placing: 1,
    },
    {
        id: "9",
        icon: "smu-logo.png",
        name: "SMU Volleyball Championships",
        capacity: 48,
        format: "round-robin",
        band: "upper",
        startDate: new Date("2024-10-20T09:00:00").toISOString(),
        endDate: new Date("2024-11-05T18:00:00").toISOString(),
        signupStartDate: new Date("2024-10-01T09:00:00").toISOString(),
        signupEndDate: new Date("2024-10-19T23:59:00").toISOString(),
        status: "UPCOMING",
        signUpPercentage: 75,
        numberOfSignups: 36,
        timeWeight: 35,
        memWeight: 25,
        testCaseWeight: 40,
        currentRound: "Group Stage",
        currentRoundEndDate: new Date("2024-11-02T18:00:00").toISOString(),
        signedUp: true,
        participated: false,
        signupsOpen: true,
        placing: -1,
    }
];

export const notificationData2 = [
    {
        "id": "1",
        "username": "johndoe",
        "tournamentId": "101",
        "tournamentName": "SMU Chess Open",
        "message": "Round Started",
        "type": "Round Started",
        "category": "notification",
        "createdAt": "2024-10-12T09:30:00Z",
        "isRead": false
    },
    {
        "id": "2",
        "username": "janedoe",
        "tournamentId": "102",
        "tournamentName": "SMU Tennis League",
        "message": "Tournament Started",
        "type": "Tournament Started",
        "category": "alert",
        "createdAt": "2024-10-12T10:00:00Z",
        "isRead": false
    },
    {
        "id": "3",
        "username": "alexsmith",
        "tournamentId": "103",
        "tournamentName": "SMU Coding Marathon",
        "message": "Round Started",
        "type": "Round Started",
        "category": "notification",
        "createdAt": "2024-10-12T11:15:00Z",
        "isRead": true
    },
    {
        "id": "4",
        "username": "emilywhite",
        "tournamentId": "104",
        "tournamentName": "SMU Soccer Showdown",
        "message": "Tournament Started",
        "type": "Tournament Started",
        "category": "alert",
        "createdAt": "2024-10-12T12:45:00Z",
        "isRead": false
    },
    {
        "id": "5",
        "username": "charliebrown",
        "tournamentId": "105",
        "tournamentName": "SMU Volleyball Championships",
        "message": "Round Started",
        "type": "Round Started",
        "category": "notification",
        "createdAt": "2024-10-13T08:20:00Z",
        "isRead": true
    },
    {
        "id": "6",
        "username": "lucasmiller",
        "tournamentId": "106",
        "tournamentName": "SMU Basketball Dunk Fest",
        "message": "Tournament Started",
        "type": "Tournament Started",
        "category": "alert",
        "createdAt": "2024-10-13T09:00:00Z",
        "isRead": false
    },
    {
        "id": "7",
        "username": "gracejohnson",
        "tournamentId": "107",
        "tournamentName": "SMU Badminton Open",
        "message": "Round Started",
        "type": "Round Started",
        "category": "notification",
        "createdAt": "2024-10-13T09:30:00Z",
        "isRead": true
    },
    {
        "id": "8",
        "username": "michaelng",
        "tournamentId": "108",
        "tournamentName": "SMU Swimming Gala",
        "message": "Tournament Started",
        "type": "Tournament Started",
        "category": "alert",
        "createdAt": "2024-10-13T10:15:00Z",
        "isRead": false
    },
    {
        "id": "9",
        "username": "sophiachan",
        "tournamentId": "109",
        "tournamentName": "SMU Coding Hackathon",
        "message": "Super long message to test CSS stuff because I have no idea how else to test to be very honest wth you, Super long message to test CSS stuff because I have no idea how else to test to be very honest wth you",
        "type": "Round Started",
        "category": "notification",
        "createdAt": "2024-10-13T11:00:00Z",
        "isRead": false
    }
];
