export const profileUsers = [
    {
      id: 1,
      name: 'AdrianLooLovesCoding',
      email: 'adrianloo@gmail.com',
      profilePicture: '/profile-picture.jpg',
      elo: 2350,
      matchesPlayed: 256,
      wins: 154,
      losses: 102,
    //   recentOpponents: ['Opponent 1', 'Opponent 2', 'Opponent 3'],
    },
    {
      id: 2,
      name: 'JohnDoe',
      email: 'johndoe@example.com',
      profilePicture: '/profile-picture2.jpg',
      elo: 2000,
      matchesPlayed: 150,
      wins: 100,
      losses: 50,
    //   recentOpponents: ['Opponent 4', 'Opponent 5', 'Opponent 6'],
    },
    {
      id: 3,
      name: 'JaneDoe',
      email: 'janedoe@example.com',
      profilePicture: '/profile-picture3.jpg',
      elo: 2500,
      matchesPlayed: 300,
      wins: 200,
      losses: 100,
    //   recentOpponents: ['Opponent 7', 'Opponent 8', 'Opponent 9'],
    },
  ];